CREATE DATABASE tata;
SHOW DATABASES;
USE tata;

CREATE TABLE Worker (
    WORKER_ID INT PRIMARY KEY,
    FIRST_NAME VARCHAR(50) NOT NULL,
    LAST_NAME VARCHAR(50) NOT NULL,
    DEPARTMENT VARCHAR(50) NOT NULL,
    SALARY DECIMAL(10,2) NOT NULL
);

INSERT INTO Worker VALUES
(1, 'Vishal', 'anto', 'HR', 85000.00),
(2, 'Rithika', 'Syesh', 'Finance', 120000.00),
(3, 'Naveen', 'Sara', 'IT', 95000.00),
(4, 'Ani', 'Sneha', 'Marketing', 110000.00),
(5, 'Sundarash', 'shami', 'HR', 70000.00),
(6, 'Divya', 'praveen Kumar', 'IT', 105000.00),
(7, 'Vivek', 'Sri', 'Admin', 250000.00),
(8, 'Manu', 'Suresh', 'Finance', 125000.00);

SELECT * FROM Worker;

SELECT * FROM Worker
WHERE DEPARTMENT = 'IT' AND SALARY > 100000;

SELECT * FROM Worker
WHERE DEPARTMENT = 'HR' OR SALARY < 80000;

SELECT * FROM Worker
WHERE NOT DEPARTMENT = 'Finance';

SELECT * FROM Worker
WHERE SALARY > 80000 AND (DEPARTMENT = 'IT' OR DEPARTMENT = 'Finance');

SELECT * FROM Worker 
WHERE WORKER_ID IN (1,5,6,8) AND SALARY >= 10000;

SELECT * FROM Worker
WHERE WORKER_ID NOT IN (2,4,6,8);

SELECT * FROM Worker
WHERE DEPARTMENT NOT IN ('HR', 'Admin') AND SALARY BETWEEN 70000 AND 300000;

SELECT * FROM Worker
WHERE FIRST_NAME LIKE 'V%' AND SALARY >= 200000;

SELECT * FROM Worker
WHERE DEPARTMENT NOT IN ('Admin') AND SALARY < 100000;

SELECT MIN(SALARY) AS Minimum_Salary FROM Worker;

SELECT * FROM Worker
WHERE SALARY = (SELECT MAX(SALARY) FROM Worker);

SELECT AVG(SALARY) AS Avg_Admin_Salary
FROM Worker
WHERE DEPARTMENT = 'Admin';

SELECT SUM(SALARY) AS Total_HR_Admin_Salary
FROM Worker
WHERE DEPARTMENT IN ('HR', 'Admin');

SELECT SUM(SALARY) AS Total_HR_Admin_Salary
FROM Worker
WHERE DEPARTMENT IN ('HR', 'Admin');

SELECT COUNT(*) AS Count_V
FROM Worker
WHERE FIRST_NAME LIKE 'V%';

SELECT SUM(SALARY) AS Total_Salary_Range
FROM Worker
WHERE SALARY BETWEEN 50000 AND 200000;

SELECT FIRST_NAME FROM Worker
UNION 
SELECT LAST_NAME FROM Worker;

SELECT FIRST_NAME, SALARY,
CASE 
    WHEN SALARY < 50000 THEN 'poor'
    WHEN SALARY BETWEEN 50000 AND 150000 THEN 'med-class'
    ELSE 'rich'
END AS StatusBasedOnSalary
FROM Worker;